### ISSUE TITLE
Crash the server due to Russian translation

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#10]
++#ServerAuth plugin Russian language file
++#Translation by Pub4Game

Please remove "+"

**Comment by Flavius12** [comment]
Russian translation updated. Can you check if it crash anymore?
Thank you :)

**Comment by Pub4Game** [comment]
Now it works)) I accidentally put "+"

**Comment by Flavius12** [comment]
Perfect! :D
Let me know if you find any other bug or suggestion. Thank you :)
