### ISSUE TITLE
Please add Xbox Live

### ISSUE THREAD

**Issue by MrDoni98** [EvolSoft/ServerAuth#104]
Please add support Xbox Live

**Comment by SalmonDE** [comment]
You could do a plugin extension for ServerAuth to implement XBox Live Authentication

**Comment by thelucyclub** [comment]
If it's so easy? Why don't you do it?
I don't have enough time, or I would. But I am also not good with Xbox realated things on MCPE.

**Comment by TheDiamondYT1** [comment]
@thelucyclub Who is that aimed at

**Comment by thelucyclub** [comment]
@SalmonDE

**Comment by SalmonDE** [comment]
@thelucyclub Where did I state that this was easy? I was just saying that this could be done by an extension, since back then this repo seemed to be inactive.

**Comment by inxomnyaa** [comment]
@thelucyclub wtf go and offend someone else. salmon was simply giving a helful information for a current workaround, not a letter that says "i'll kill you"
