### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by VCraftMCPE** [EvolSoft/ServerAuth#105]
i did try to setup my sql for server auth but it wont work i tried the same sql in HereAuth and it work fine
im sure its a server auth bug please fix

**Comment by Flavius12** [comment]
Check your ServerAuth configuration better. Don't forget that ServerAuth works only with **MySQL** and you must set an empty database/table

**Comment by VCraftMCPE** [comment]
i did and it not works
always ServerAuth when i enable MySql get disabled test it and see

**Comment by SalmonDE** [comment]
MySQL works fine for me

**Comment by Flavius12** [comment]
@VCraftMCPE please post a console error log or something like it otherwise how can I know if it's a bug or a wrong configuration?

**Comment by VCraftMCPE** [comment]
#MySQL host
  host: "sql.host.com"
  #MySQL port (default 3306)
  port: 3306
  #MySQL username
  username: mcusersxx"
  #MySQL password (you can leave it blank if your database doesn't need password)
  password: "passwords"
  #MySQL ServerAuth database
  database: "mcusersxx"
  #ServerAuth table prefix
  table_prefix: "SrvAuth_"
tell me what is wrong??

**Comment by VCraftMCPE** [comment]
2016-08-25 [13:47:55] [Server thread/INFO]: Enabling ServerAuth v2.13
2016-08-25 [13:47:55] [Server thread/CRITICAL]: ClassNotFoundException: "Class mysqli not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
2016-08-25 [13:47:55] [Server thread/INFO]: Disabling ServerAuth v2.13

**Comment by SalmonDE** [comment]
@VCraftMCPE Check if your binarys have the mysqli extension

**Comment by Flavius12** [comment]
You must install the PHP MySQLi extensions in order to use MySQL database functionalities on ServerAuth

**Comment by VCraftMCPE** [comment]
how to?

**Comment by VCraftMCPE** [comment]
i have no idea

**Comment by SalmonDE** [comment]
@VCraftMCPE What server software do you use? (PocketMine-MP, ClearSky, Genisys ...)

**Comment by VCraftMCPE** [comment]
Genisys

**Comment by SalmonDE** [comment]
You probably needs Genisys Binarys then, however, I can't find any at the moment. So you could try the pocketmine one's or the one's on my repo.

**Comment by VCraftMCPE** [comment]
im using MCPE host virtualgladiators.com so i cant install it

**Comment by VCraftMCPE** [comment]
dude how to do that ? im using virtualgladiators.com

**Comment by SalmonDE** [comment]
@VCraftMCPE Contact their support and ask if they could fix the issue. You need the MySQLi extension in your binarys in order to use mysql in this plugin. (And many others)

**Comment by VCraftMCPE** [comment]
i did thanks.
