### ISSUE TITLE
Item disappear bug

### ISSUE THREAD

**Issue by sero583** [EvolSoft/ServerAuth#108]
If the Player isn't logged in and someone goes into his Account and Drops the Items, they'll disappear forever, please fix this asap

**Comment by TDMidkwhatisxd** [comment]
Is genisys bug

**Comment by zKoz210** [comment]
@TheDiamondYT1 invalid, close

**Comment by TheDiamondYT1** [comment]
You don't need to tag me, i'm notified for every comment
