### ISSUE TITLE
XBox Auth & Password Chat block

### ISSUE THREAD

**Issue by u63725** [EvolSoft/ServerAuth#111]
Can you add XBox Auth and a Password block function for the chat that no Player can write his Password in the Chat :)

**Comment by SalmonDE** [comment]
@HydrexHD To answer your second question: https://github.com/EvolSoft/ChatLogin



###### Edited by TheDiamondYT1

**Comment by thelucyclub** [comment]
thats not what he said.

**Comment by SalmonDE** [comment]
@thelucyclub It works out for the second thing.

**Comment by TheDiamondYT1** [comment]
@SalmonDE *edited your comment*

**Comment by TheDiamondYT1** [comment]
Xbox live support should be discussed in #104
