### ISSUE TITLE
register command freeze server

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [EvolSoft/ServerAuth#114]
https://timings.aikar.co/?url=23424624

**Comment by TDMidkwhatisxd** [comment]
I banned someone , he changed name and used /register and crashed server, any fix?!?!?!?

**Comment by NordicWarrior** [comment]
For me too. Command register overloads the server.

**Comment by TDMidkwhatisxd** [comment]
Nope, there is a secret to make it overload server!

If u use it normaly it should be fine!

What u do?

**Comment by TDMidkwhatisxd** [comment]
If i can reproduce i can do tests and patch it

**Comment by TDMidkwhatisxd** [comment]
� cause freeze in register
� <= is this dude fault. Xd

I will add a filtrer !!!

Failed ;-; 

I will try a workaround

**Comment by fycarman** [comment]
/register freezes the server only if you limit the number of account per-ip, because it will check in every player file if the ip is the same as the ip of the player who is registering.

**Comment by TDMidkwhatisxd** [comment]
Are u sure? Many players used /register and the only one with that strange symbol freezed the server for 20 seconds!
Thanks! I will try like u told me !

**Comment by TDMidkwhatisxd** [comment]
But something is missing! Why it not happen always? Becouse players register every 10 seconds xdxdxd!
