### ISSUE TITLE
You forget to add a public function

### ISSUE THREAD

**Issue by mihnea91** [EvolSoft/ServerAuth#115]
In EventListener you must add this function
```php
public function onBlockBreak(BlockBreakEvent $event){
    	if($this->plugin->getConfig()->getAll()["block-all-events"]){
    		if(!ServerAuth::getAPI()->isPlayerAuthenticated($event->getPlayer())){
    			$event->setCancelled(true);
```
without it every man who eneter with name of other player, is able to break blocks although the account isn't logged in.

###### Edited by TheDiamondYT1

**Comment by zKoz210** [comment]
@TheDiamondYT1 fixed long time ago
