### ISSUE TITLE
MySQL Table

### ISSUE THREAD

**Issue by ghost** [EvolSoft/ServerAuth#117]
The plugin MySQL is connecting, but at the beginning of the table name I want it says serverauth.
I do not want to write serverauth.

**Comment by Flavius12** [comment]
Do you mean the database name or the tables name?
Can you be more detailed?

**Comment by ghost** [comment]
Yeah. The name of the table I select is "uyeler" but it is created in the MySQL table as "uyelerserverauthdata".

**Comment by Flavius12** [comment]
It's not a bug. You can only change the tables' prefix, not the name.

**Comment by ghost** [comment]
Ok. Thanks.
