### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by ghost** [EvolSoft/ServerAuth#121]
CRITICAL> TypeError: "Return value of ServerAuth\ServerAuth::initializeDatabase() must be of the type boolean, none returned" (EXCEPTION) in "/plugins/ServerAuth/src/ServerAuth/ServerAuth" at line 263

**Comment by zKoz210** [comment]
@Flavius12 fixed https://github.com/EvolSoft/ServerAuth/pull/127
