### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by Gecekatili** [EvolSoft/ServerAuth#123]
Hello there! I noticed the turkish language support of the ServerAuth plugin. I prepared a Turkish language support for this.
http://www.dosya1.com/OoQHfM

**Comment by Flavius12** [comment]
Thank you! Perfect! Turkish language will be added in ServerAuth v3.0!

**Comment by Flavius12** [comment]
Language should be updated following the new format. See **EN_en.yml** template for all definitions.

**Comment by Gecekatili** [comment]
Oh, okay. I will prepare a new TR_tr.yml file within 1 - 2 days.

15 May 2018 Sal 00:34 tarihinde Flavius12 <notifications@github.com> şunu
yazdı:

**Comment by Gecekatili** [comment]
Update v3.0 TR_tr.yml

15 May 2018 Sal 08:03 tarihinde Ramazan Lafçı <parapul41@gmail.com> şunu
yazdı:

**Comment by Flavius12** [comment]
Thank you for your contribution! :+1:
