### ISSUE TITLE
error

### ISSUE THREAD

**Issue by VCraftMCPE** [EvolSoft/ServerAuth#124]
17.07 10:30:56 [Server] Server thread/CRITICAL TypeError: "Return value of ServerAuth\ServerAuth::initializeDatabase() must be of the type boolean, none returned" (EXCEPTION) in "/ServerAuth_v2.13.phar/src/ServerAuth/ServerAuth" at line 263

**Comment by inxomnyaa** [comment]
Means the connection could not be established, check your settings
