### ISSUE TITLE
my server lags on /register

### ISSUE THREAD

**Issue by SuperKali** [EvolSoft/ServerAuth#133]
The server stops for a moment and after a while it resumes running

**Comment by VCraftMCPE** [comment]
it doesnt happen to me

**Comment by inxomnyaa** [comment]
https://github.com/EvolSoft/ServerAuth/blob/master/ServerAuth/src/ServerAuth/ServerAuth.php#L627
try to put `print time();` before and after this line and register again. If the difference between the timestamps is huge the connection to the database is slow.

**Comment by TheDiamondYT1** [comment]
I wish i could fix this but i don't have a 64 bit PHP binary for Android :(

**Comment by SuperKali** [comment]
i dont use database i use yaml

**Comment by Flavius12** [comment]
A better user cache system will come with ServerAuth v3.0 update!
