### ISSUE TITLE
WebAPI

### ISSUE THREAD

**Issue by xHFx** [EvolSoft/ServerAuth#15]
Upon adding the ServerAuth Account Manager to my server I tried to make the admin account and after following the steps of adding username and a password it just reload and did nothing at all. I simply draged files in and register and got nothing!

**Comment by Flavius12** [comment]
Did you check all requirements? (PHP version, MySQL version, ...)
However keep in mind that the main goal of the ServerAuth Account Manager is to show and explain how the ServerAuth WebAPI works

**Comment by xHFx** [comment]
I setb.com/up mysql but not a database for this ... I shouldnt need to connect a database just to register the admin account

**Comment by Flavius12** [comment]
Yes but you must check PHP version anyway

**Comment by xHFx** [comment]
Running latest php... Im hosting my forums on same server ... darkrealms.cf/forums/

**Comment by Flavius12** [comment]
Try latest ServerAuthAccountManager. Enable debug and see if it logs error. Then, if you see errors, report them here

**Comment by xHFx** [comment]
Alright , I love you :* :100:
