### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#16]
The plugin was tested on hosting

ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/ServerAuth_v1.10 (1).phar/src/ServerAuth/ServerAuth" at line 257

:(

**Comment by Flavius12** [comment]
The bug is related to the automatic languages file saving on Unix systems. Read the first item of the list in the issue #14
I'm working on a way to fix this.
Thank you for report :)

**Comment by Pub4Game** [comment]
@Flavius12 When do you plan to release an update? I really need your plugin)

**Comment by Flavius12** [comment]
Maybe today. Depends on bug fix time

**Comment by Flavius12** [comment]
Fixed :)
