### ISSUE TITLE
incorrect display of messages

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#17]
If require-password: true, when I write /unregister <password> I hope you can unregister message-success: "&aYou are now unregistered!"

If require-password: false, when I write /unregister <password> writes me a message 
user-not-authenticated: "&can you are not logged in!"

Although I have registered and signed in to your account.

**Comment by Flavius12** [comment]
Yes, I noticed the typo. I'm fixing it now.
Thank you :)

**Comment by Pub4Game** [comment]
@Flavius12 You did not fix it right)

permissions:
 serverauth:
  default: true <-------- True :)
  description: ServerAuth commands permissions.
  children:
   serverauth.help:
    default: true
    description: Allows player to show ServerAuth help.

**Comment by Pub4Game** [comment]
@Flavius12 You didn't correct permission /sa help

**Comment by Flavius12** [comment]
@Pub4Game See https://github.com/EvolSoft/ServerAuth/blob/master/ServerAuth/plugin.yml#L38

**Comment by Pub4Game** [comment]
@Flavius12 OK, then go to the game and check!

**Comment by Pub4Game** [comment]
@Flavius12 When will the fix? I would like to see it in ServerAuth 'accounts that are using the same unique id (ip + clientId + name) when logging in again will be automatically authenticated"

**Comment by Flavius12** [comment]
You must enable IP login from ServerAuth configuration
