### ISSUE TITLE
Hmm...

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#18]
In the plugin there is a strange bug, if I things "/give Pub4Game 20 32" you won't see them in the inventory, we will need to move to the server

**Comment by Flavius12** [comment]
What does it have to do with serverauth?

**Comment by Pub4Game** [comment]
Don't know, but after installing Your plugin, this problem occurs.

**Comment by Flavius12** [comment]
The plugin doesn't manage inventories at all

**Comment by Pub4Game** [comment]
Please check it yourself, it's a pretty big problem!

**Comment by Flavius12** [comment]
Ok. Now I check

**Comment by Pub4Game** [comment]
@Flavius12  checked?

**Comment by Flavius12** [comment]
Yes and this problem doesn't happen on my server. As you can also see on the source code of this plugin, it doesn't manage the player inventory

**Comment by Pub4Game** [comment]
Video showing the bug.

plugins: DevTools, ServerAuth

PM - 1258

http://youtu.be/MAvtAAOhZWU

**Comment by Pub4Game** [comment]
@Flavius12 I have studied the bug in more detail. This bug happens when the player logs into the game for the first time. If you re-enter this bug disappears.

**Comment by Flavius12** [comment]
Have you tried without ServerAuth?
Try to join for the first time and then try the give command.
If you have still this problem it's not related to ServerAuth

**Comment by Pub4Game** [comment]
Yes, without ServerAuth everything works perfectly! I really need your plugin

**Comment by Flavius12** [comment]
Yes. The problem is that I don't know why it happens and ServerAuth doesn't manage inventories at all

**Comment by Flavius12** [comment]
Wait. Maybe...
On the ServerAuth configuration set block-all-events to false. Then try to use the /give command. Let me know if it works (the problem may be in one of those events)

**Comment by Pub4Game** [comment]
Yes, indeed the problem in block-all-events. As soon as you solve that?

**Comment by Flavius12** [comment]
What? Did it work with block-all-events disabled?
I'll solve this bug as soon as possible. Just the time to finish a C++ project. But if I have time I'll work also today on ServerAuth

**Comment by Pub4Game** [comment]
Yes, it worked! Thank You very much for quick fixes) like Your plugin to our hosting clients.

**Comment by Flavius12** [comment]
Thank you for all your reports. You are contributing a lot to this project. Now I'll try to understand what is the event which causes this bug
