### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#20]
I found one very strange bug. 
If the server comes OP with IP e.g. 127.0.0.1, and then re-enter with this nick, and another ip 123.122.23.1, then asks everyone to re-enter the password. All including those who have already entered the login and password.

**Comment by Flavius12** [comment]
Can you explain better?

**Comment by Pub4Game** [comment]
I think the error in - IPLogin: true
If the player comes with OP on a server with ip address for example 127.123.12.13, then re-enters the server with a different ip, the authentication is all cleared and all players have to re-write /login

Sorry, I translated in Google

**Comment by Flavius12** [comment]
Now I understand. This is strange...
I'll try the IP login with more than two players on the server.

**Comment by Pub4Game** [comment]
@Flavius12 When You have the time to fix all the bugs?

**Comment by Flavius12** [comment]
After finishing a C++ project :)

**Comment by Pub4Game** [comment]
I hope this is not a very long time)
