### ISSUE TITLE
Logged in from another location

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#21]
If a player comes from the nickname of a player who is already playing on the server kick them both and says "sardor disconnected: Kicked by admin. Reason: logged in from another location ."
I would like to see the ability to disable this feature, but my player is not very happy.

**Comment by Flavius12** [comment]
Yes. The kick process for same nicknames doesn't work very well but I'm working on a better way to make it working

**Comment by Flavius12** [comment]
Actually ServerAuth doesn't have a system to kick players when they use a nickname already used in game. This means that this problem is related to PocketMine. In the future releases of ServerAuth a kick system for different locations logins may be implemented

**Comment by Pub4Game** [comment]
I used the code from SimpleAuth)) I'll wait for the release of a new plugin version, how long approximately it will be released?

**Comment by Flavius12** [comment]
As I said before I must finish a C++ project before releasing a new version of this plugin

**Comment by Pub4Game** [comment]
How many do you need time to finish the project?

**Comment by Flavius12** [comment]
A year. But don't worry I'll finish some plugins updates (also this) before continuing that project

**Comment by Pub4Game** [comment]
I and others really need to fix! It will be at least 0.12.1?

**Comment by Flavius12** [comment]
It should work also with 0.12.1

**Comment by Flavius12** [comment]
Added in v2.00!
