### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#24]
As you finish a C++ project, could you add:
1)Invisibility of players until they log in to your account
2)to Add more events
3)Add constraint registrations under "->getClientId()" (Not sure if I'm allowed)
4)Add automatic teleporting to spawn when you log on to the server.
tpSpawn: true/false
5)To add, the function of a temporary ban, if a certain number of times incorrectly entered the password
6)To make a command /unregister name, /changepassword name password, /logout name
7)To make the list of banned nicks

I would be interested to hear your opinion on these ideas

**Comment by Pub4Game** [comment]
@Flavius12 What do you think about this?

**Comment by Flavius12** [comment]
1) **Will be done** on a different plugin (a ServerAuth extension)
2) What kind of events do you want? The _EntityDamageEvent_ will be added
3) **Won't be added**
4) **Won't be added**. Use another plugin like MSpawns to do this
5) **Will be added** but only with kick (tempban may be added in future)
6) **Already added**
7) **Won't be added**

**Comment by Pub4Game** [comment]
Thank you :+1:

**Comment by Flavius12** [comment]
You are welcome :+1:
The new update will be released in some hours :smile:. Just the time to complete the To-Do list.
Thank you :+1:

**Comment by Pub4Game** [comment]
Your plugin I would have given 5 stars)

**Comment by Flavius12** [comment]
Thank you :smiley:
