### ISSUE TITLE
Problem with /reload

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#25]
If you write /reload, then a couple seconds ServerAuth will require to enter a password /login <password>, where players can walk, break the blocks to write in the chat! This bug remains until a full restart of the server.

**Comment by Flavius12** [comment]
This bug has been fixed on the new version. It will be released today.

**Comment by Pub4Game** [comment]
@Flavius12 Another bug with /sa help, players don't have the rights to use this command

**Comment by Flavius12** [comment]
That's strange:
![image](https://cloud.githubusercontent.com/assets/10297075/9579456/0570bfc8-4ff3-11e5-96a3-90b5686752e6.png)
See ^

**Comment by Pub4Game** [comment]
I do understand this. But check it out in game!

**Comment by Flavius12** [comment]
No problem. I fixed it. The problem was in plugin.yml file

**Comment by Flavius12** [comment]
Thank you :smile:

**Comment by Pub4Game** [comment]
:+1:

**Comment by Pub4Game** [comment]
My fix for the bug with the inventory will be in To-Do?

**Comment by Flavius12** [comment]
Your fix has already been done. Now I add it in the To-Do list

**Comment by Flavius12** [comment]
@Pub4Game join gitter.im chat. I must ask you one thing

**Comment by Flavius12** [comment]
Fixed in v2.00
