### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#29]
(If you write /reload and log back on the server, I have not asked to enter /login password, but I can't break blocks) - no bug

Crash

Fatal error: Call to undefined method pocketmine\event\entity\EntityDamageByBlockEvent::getPlayer() in C:\PocketMine-MP\plugins\ServerAuth1234\src\ServerAuth\EventListener.php on line 172

**Comment by Flavius12** [comment]
Ok. I fix it now :)

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/9582133/3321ecb2-500c-11e5-886c-573c4060a945.png)

Strange force-single-auth

enable-failed-logins-kick: true

**Comment by Flavius12** [comment]
Can you be more detailed?

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/9582247/d6213fd0-500c-11e5-80dd-d6d6a970d7ae.png)
1) Why if not logged in, enable-failed-logins-kick not working?
2) there is No reason kick "Lost connection with server"

**Comment by Flavius12** [comment]
1) It's not a bug. The kick works only when a player is logged in **and authenticated**
2) MCPE bug

**Comment by Pub4Game** [comment]
2)Your error!

**Comment by Pub4Game** [comment]
1) It is not very convenient, think about it some players can interfere with other players to log on the server

**Comment by Flavius12** [comment]
2) It's an MCPE bug. I used the kick function correctly

**Comment by Pub4Game** [comment]
:(

**Comment by Flavius12** [comment]
One time I reported this bug to @shoghicp

**Comment by Pub4Game** [comment]
After authorization, the blocks do not break((

**Comment by Pub4Game** [comment]
Sorry, bug with breaking blocks no :)

**Comment by Flavius12** [comment]
Fixed in v2.10

**Comment by Pub4Game** [comment]
Thank you very tried today)) :+1:
