### ISSUE TITLE
max login attempts bug

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#32]
max-login-attempts does not work( the Player does not kick, if he enters more than 5 times wrong password

max-login-attempts: 5
enable-failed-logins-kick: true

**Comment by Flavius12** [comment]
Strange. I tested it and it worked for me

**Comment by Flavius12** [comment]
Please use the latest configuration file. If you can, post yours

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/9603071/b2cdfc1c-50b6-11e5-9186-97fe272a804a.png)

I used the standard configuration

**Comment by Flavius12** [comment]
Can you post your configuration file here?

**Comment by Flavius12** [comment]
Only the login part

**Comment by Pub4Game** [comment]
login:
  #Enable login on your server
  enabled: true
  #Enable failed logins kick
  enable-failed-logins-kick: true
  #Max number of attempts
  max-login-attempts: 5
  #Login message interval
  message-interval: 30

**Comment by Flavius12** [comment]
No problem. I found the bug. I forgot to add the function when using configuration files instead of MySQL

**Comment by Pub4Game** [comment]
You will fix it today?

**Comment by Flavius12** [comment]
No, I don't. Tomorrow I'll fix it

**Comment by Flavius12** [comment]
Fixed in v2.11

**Comment by Pub4Game** [comment]
Thanks :+1:

**Comment by Flavius12** [comment]
:+1:
