### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#33]
ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/ServerAuth_v2.11.phar/src/ServerAuth/EventListener" at line 112

**Comment by HotFireyDeath** [comment]
Maybe $i is not defined? I don't see a define statement for var $i you used on that line. Perhaps I'm missing something?

**Comment by HotFireyDeath** [comment]
Never mind, upon closer examination $i wasn't quite the issue.

**Comment by Flavius12** [comment]
Fixed in v2.12
