### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AndreyNazarchuk** [EvolSoft/ServerAuth#34]
Please make it so players don't have to use /login or /register so they can just type their password into chat.
Thanks. :D

**Comment by Pub4Game** [comment]
use https://github.com/EvolSoft/ChatLogin

**Comment by legoboy0215** [comment]
Use the ChatLogin plugin...

On Mon, Sep 14, 2015 at 12:30 PM, Andrey Nazarchuk <notifications@github.com

**Comment by AndreyNazarchuk** [comment]
@Pub4Game @legoboy0215 Thanks :)

**Comment by PEMapModder** [comment]
I simply don't see the difference. Except that it is actually easier to listen from chat directly rather than via a command.
