### ISSUE TITLE
SQLite Support?

### ISSUE THREAD

**Issue by TheDiamondYT1** [EvolSoft/ServerAuth#39]
Maybe add this

**Comment by Flavius12** [comment]
I've never worked with SQLite but I may add this feature.
Keep in mind that people usually uses MySQL instead of any other SQL software. I recommend the use of MySQL instead

**Comment by TheDiamondYT1** [comment]
SQLite is already in pocketmine. It is easy to use it creates a FileName.db. look at factionspro.

**Comment by TheDiamondYT1** [comment]
``` php
private $db;

//On enable
$this->db = new \SQLite 
```

I think

**Comment by TheDiamondYT1** [comment]
Havent used in a while.

**Comment by Flavius12** [comment]
Ok. I'll see how it works
