### ISSUE TITLE
/login

### ISSUE THREAD

**Issue by GODLIKE5** [EvolSoft/ServerAuth#41]
Can this be simplified to just type their password? If not... Please add it and if so tell me how

**Comment by Pub4Game** [comment]
Yes, it is already there, use ChatLogin 
https://github.com/EvolSoft/ChatLogin

**Comment by GODLIKE5** [comment]
Thxs

**Comment by Flavius12** [comment]
Give a star to the plugin if you like it :smile: 
Thank you
