### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by GODLIKE5** [EvolSoft/ServerAuth#42]
Ok so i was playing and i saw alot of lag and i took all my maps and plugins exept ChatLogin and ServerAuth.. Then the lag was still there.. Any way to fix? Or make a lagg free auth

**Comment by AndreyNazarchuk** [comment]
Now try putting everything back and just removing chat login, if lag is
still there then put it back and remove ServerAuth. If lag is gone that
means it was ServerAuth's fault. The way you tried to test what was making
it lag is very dumb because you have no way of knowing if its just your
server that is slow.

**Comment by GODLIKE5** [comment]
I already tried all i just left ServerAuth.. And it lags badly even players report lag

**Comment by AndreyNazarchuk** [comment]
Now try it WITHOUT ServerAuth and a similar amount of players.

**Comment by Flavius12** [comment]
When I release my plugins I always do performance tests.
These tests consist on testing the plugin on my computer first, then I test it on an older computer with PocketMine and also on a Koding VPS (1 core, 1 GB RAM). In this way I'm sure that the plugin doesn't require lot of CPU/RAM.
When I did the performance test of ServerAuth I didn't find any lag. This means that the lags you're having may depend from the amount of players on your server, the PocketMine version you're using, the hardware or from conflicts with other plugins.
Can you post where you are running PocketMine (hardware details)? Is it a VPS?
Then which PocketMine build are you running? And which is the mid amount of players who play on your server? Also which plugins are you running?

**Comment by GODLIKE5** [comment]
15 player slots. Pocketmine 12.1 dev #48 and a total of 23 plugins.. Hosted on a windows pc 268gb ram and i have gave my server a ram of 2046m. Before that plugin it was fine... Then it messed up. Now i currently have just SimpleAuth snd SimpleAuth Helper instead of urs :(

**Comment by Flavius12** [comment]
How can you have 268 GB!?
Yes but I think your server will lag anyway. Bleeding builds are very unstable and they have lots of lags.

**Comment by GODLIKE5** [comment]
My dad has paid for them to add more ram and more space in the hard drive

**Comment by PEMapModder** [comment]
268 GB RAM? That's not even reasonable... Not even production servers need that much RAM... Did you mean 268 GB harddisk?

**Comment by AndreyNazarchuk** [comment]
Lol, that's probably why this thread was closed. The author realized this
kid is perfectly unreasonable.

**Comment by GODLIKE5** [comment]
Yeah.. Im not sure if thats ram... Im more of an android user..

**Comment by AndreyNazarchuk** [comment]
The 256GB is probably storage, ram is probably not the problem. Either your
CPU has a very low single core speed or your storage is an HDD.

**Comment by GODLIKE5** [comment]
My dad has paid for them to add more ram and more space in the hard drive

**Comment by AndreyNazarchuk** [comment]
That does not mean anything. What are the specs? For 15 players, processor
should be at least 2.0GHz, at least 512mb ram, and at least 5GB of SSD
storage

**Comment by GODLIKE5** [comment]
Hey guys i am back.... well it wasn't that... the problem was my desktop computer.. it had an old update of windows 7 and after the update it works fine now.. :)
