### ISSUE TITLE
ServerAuth Account Manager

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#43]
![image](https://cloud.githubusercontent.com/assets/11244874/10906488/f67b830a-8232-11e5-8157-08dbc4fb8d5d.png)

![image](https://cloud.githubusercontent.com/assets/11244874/10906522/33660b5a-8233-11e5-8d7e-e4a5a0e7b1ea.png)

![image](https://cloud.githubusercontent.com/assets/11244874/10906497/0552703c-8233-11e5-8b59-1651a8761c6e.png)

Bug?

and 

![image](https://cloud.githubusercontent.com/assets/11244874/10906860/0c1563d6-8236-11e5-90dc-bb05a655b9c6.png)

**Comment by Flavius12** [comment]
What happens exactly? When you click cancel do you see "Password for 'player' is too short?
Then what is the second bug exactly? Do you mean that you see tooltips on the bottom of the page?

**Comment by Pub4Game** [comment]
@Flavius12 

1) Yes)
2) tooltips? I just reload the page and they appear for a second and then disappear

**Comment by Flavius12** [comment]
About the second problem sorry but I don't understand well what do you mean. Can you explain better what happens?

**Comment by Pub4Game** [comment]
I go to the website, then update the page several times and these "tooltips" appear one second and disappear

Sorry for my bad English :unamused:

**Comment by Flavius12** [comment]
Maybe a browser bug?

**Comment by Pub4Game** [comment]
Hmm... I use Google Chrome
