### ISSUE TITLE
Uhm...

### ISSUE THREAD

**Issue by ghost** [EvolSoft/ServerAuth#45]
[18:36:25] [Server thread/WARNING]: RuntimeException: "fopen(/home/game/plugins/ServerAuth/languages/EN_en.yml): failed to open stream: No such file or directory" (E_WARNING) in "/src/pocketmine/plugin/PluginBase" at line 213

**Comment by Pub4Game** [comment]
Most likely you have incorrectly edited the file

**Comment by Patra3** [comment]
Does that file exist in the specified directory?

**Comment by Flavius12** [comment]
I've never found this bug before. Did you modify the plugin source code?
I'll do other tests on Linux but as I said I've never found this bug.
However if the problem persists, you can get the file from this project and you can put it on ServerAuth/languages folder manually.
This is the link of the file: https://github.com/EvolSoft/ServerAuth/blob/master/ServerAuth/resources/languages/EN_en.yml

**Comment by ghost** [comment]
my friend setup the plugin into his server and met this, no editing

**Comment by Flavius12** [comment]
So tell your friend to download the EN_en.yml file manually
