### ISSUE TITLE
Enter a email

### ISSUE THREAD

**Issue by RocoWayne** [EvolSoft/ServerAuth#55]
Can you add to the register action an email? So i can send a welcome mail to my players.

**Comment by HerO-0110** [comment]
It is extremely difficult to do this, and not to mention you have to set up a way to make your email account to send it automatically.

**Comment by PEMapModder** [comment]
Actually, you don't need an email account to send an email...

**Comment by Patra3** [comment]
@HerO-0110 It isn't difficult to do. Sending mail only requires SMTP access of a mail server. I just can't find time to do this yet.

**Comment by Flavius12** [comment]
It's not very difficult. It simply may not work in certain servers (you have to configure a mail server on the server, using postfix for example, to do this)
So, due to this problem, it won't be implemented directly in the plugin but I'll create an extension

**Comment by AndreyNazarchuk** [comment]
He's asking to implement a function that asks for an email after you
register and stores it with wherever it stores your password.

**Comment by RocoWayne** [comment]
Yes, @AndreyNazarchuk  thats right! Sorry my english, im from argentina. LifeBoat MCPE servers have this, i think that is great add on. Another idea is that the emails can storage in a MailChimp DB, so server owners can send newsletters. 

Or, maybe trougth the AccountManager.php the users can add their email.

**Comment by AndreyNazarchuk** [comment]
You can store them in the same database as the passwords, then use them as
you like.

**Comment by legoboy0215** [comment]
I use PostFix.

**Comment by RocoWayne** [comment]
what is PostFix?

**Comment by kkekof** [comment]
add it as add-on :+1:

**Comment by Flavius12** [comment]
This feature will be supported by the ServerAuth extension called EmailConfirm. It will be released together with ServerAuth v3.0!
