### ISSUE TITLE
Admin.php

### ISSUE THREAD

**Issue by bwdotdev** [EvolSoft/ServerAuth#56]
The admin.php page (after I've logged in) doesn't show any users.

**Comment by Flavius12** [comment]
Check your database settings and make sure you're using the same database for the ServerAuthAccountManager and ServerAuth plugin

**Comment by bwdotdev** [comment]
I've checked and it's all as it should be. But this is all I see...

![](https://cloud.githubusercontent.com/assets/10724949/12024304/a456aa08-ad9a-11e5-97ba-768a1732029e.PNG)

**Comment by AndreyNazarchuk** [comment]
I don't see that... My login and register pages are blank.

**Comment by legoboy0215** [comment]
Your PHP version.

**Comment by AndreyNazarchuk** [comment]
5.6 something.

**Comment by bwdotdev** [comment]
Any idea why the accounts aren't showing @Flavius12?

**Comment by Flavius12** [comment]
@SirAquarus  I think you are not using the same database for the Account Manager and for the plugin
@AndreyNazarchuk @SirAquarus However enable debug in config.php to see if there are errors. If you see errors, please post them here

**Comment by SalmonDE** [comment]
I've got the same issue. Players can still login with their ingame accounts but they don't show up in the admin Page.

**Comment by Flavius12** [comment]
Check if javascript is enabled in your browser

**Comment by SalmonDE** [comment]
@Flavius12 Checked, it's is enabled. :/. I can see the player list in the mysql database though.

**Comment by Flavius12** [comment]
@SalmonGER are you sure that the ServerAuthAccountManager configuration has the same settings as ServerAuth plugin?

**Comment by SalmonDE** [comment]
@Flavius12 Yes, i can create from the Website and the MCPE Server new accounts which show up in the mysql database
