### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by legoboy0215** [EvolSoft/ServerAuth#57]
1. OMG. Change all the isPlayerRegistered in events to isPlayerAuthed. You are executing so many queries per-second.
2. PlayerMoveEvent should be replaced with a task running every tick, checking every player.
3. @PEMapModder's suggestions :)
4. I may make a PR, but I don't have time yet.

**Comment by PEMapModder** [comment]
Using PlayerMoveEvent isn't the main problem. The problem is that you are unnecessarily querying whether a player is registered, while that can be cached (at least for this session) in PlayerMoveEvent.

**Comment by Flavius12** [comment]
Yes, you're right! Authenticated users are stored in an array in memory. Accessing it only, instead of doing also Disk I/O or database queries is 99% faster. Then, registration check in each event is useless because if the user is authenticated automatically it's also registered

**Comment by Flavius12** [comment]
@legoboy0215 About the PlayerMoveEvent why should I make a task instead of using PlayerMoveEvent?

**Comment by legoboy0215** [comment]
Check PM forums. @PEMapModder wrote a detailed post about this, with performance concerns. I'll try to make a PR, but I haven't got time yet :)

**Comment by PEMapModder** [comment]
@legoboy0215 I wrote that when you asked which one was better, and you might not be running the handler per tick. But the difference isn't really that big in this case ;)

**Comment by Flavius12** [comment]
Fixed in v2.12
