### ISSUE TITLE
Redundant event handlers

### ISSUE THREAD

**Issue by PEMapModder** [EvolSoft/ServerAuth#59]
Some of the event handlers are unnecessary. Removing them may help by improving performance _very slightly_.

| Event | Reason for redundancy |
| --: | :-- |
| PlayerBedEnterEvent | Player must interact with the bed to enter it |
| PlayerBucketFillEvent | Player must interact with liquid blocks to fill a bucket |
| PlayerBucketEmptyEvent | Similar reason |
| BlockPlaceEvent | Similar reason |
| BlockBreakEvent | Similar reason |

**Comment by legoboy0215** [comment]
Um... ItemCosume event too?

**Comment by PEMapModder** [comment]
@legoboy0215 PlayerItemConsumeEvent is not affected by PlayerInteractEvent.

**Comment by legoboy0215** [comment]
Really?

**Comment by Flavius12** [comment]
So can they be replaced with only PlayerInteractEvent?

**Comment by PEMapModder** [comment]
Yes.
You didn't add this, but same with shoot bow event. (_cough_ @xxflare)
All these should not happen if PlayerInteractEvent is cancelled.
This is theory from what I see from code. Test to confirm.

**Comment by Flavius12** [comment]
Ok. Thank you :+1:

**Comment by Flavius12** [comment]
Fixed in v2.12
