### ISSUE TITLE
Wrongly positioned code?

### ISSUE THREAD

**Issue by PEMapModder** [EvolSoft/ServerAuth#62]
This line looks suspicious. https://github.com/EvolSoft/ServerAuth/blob/master/ServerAuth/src/ServerAuth/EventListener.php#L116

**Comment by Flavius12** [comment]
Yes, you're right. I'll change that function when I understand better how setRecipients works
Thank you :smile:

**Comment by PEMapModder** [comment]
Simply move it out of your iteration loop.

**Comment by Flavius12** [comment]
Fixed in v2.12
