### ISSUE TITLE
Strengthening hash

### ISSUE THREAD

**Issue by PEMapModder** [EvolSoft/ServerAuth#64]
Hash security can be strengthened with salt. If you add the username as salt (remember to make it case-insensitive) to the password, in case the database is leaked, it is less easy to find out that two people have the same password.

**Comment by Flavius12** [comment]
Thanks for the suggestion :+1:

**Comment by PEMapModder** [comment]
Note the difficulty of backwards compatibility. You might need to hash with both algos, delete old hash and store new hash when players login so as to support hashes generated in previous versions.

**Comment by Flavius12** [comment]
Ok. I'll keep this in mind

**Comment by PEMapModder** [comment]
I just found [this](http://php.net/manual/en/faq.passwords.php#faq.passwords.fasthash) from php.net, explaining the danger of directly using a simple hash algorithm.

**Comment by PEMapModder** [comment]
This might give some inspiration https://github.com/PEMapModder/HereAuth/commit/7e5836cd40323d61cea2192f6b0d4affa6b3a0a7

**Comment by Flavius12** [comment]
Thanks :smile:

**Comment by legoboy0215** [comment]
Use password_hash. BCrypt 4 life.

**Comment by Flavius12** [comment]
A new multi hash feature is coming to the new version of ServerAuth.

**Comment by Flavius12** [comment]
Coming in v3.0
