### ISSUE TITLE
Port the data from SimpleAuth to your plugin

### ISSUE THREAD

**Issue by alex2534alex** [EvolSoft/ServerAuth#67]
I want to port the data from SimpleAuth to your plugin. Can u make a program or for porting data, or backward compatibility with SimpleAuth (which I can enable in config.yml)?

P.S.: In my opinion, it will be easier to make backward compatibility.

**Comment by Flavius12** [comment]
It's not very easy because SimpleAuth uses multiple encryption algorithms. However I will try to do it

**Comment by alex2534alex** [comment]
@Flavius12 , I know how to do simple plugin for porting data. U must make some changes in SimpleAuth. With this plug-in players themselves will port their data. How? The first step is remove the possibility of registration. In SimleAuth already exist check the correctness of the password, and there u must add this algorithm: if passwd correct, hash password to SHA256 (or other) and create new "player.yml" for ServerAuth; else, show message "Wrorg password. Is it your account? —_—"

**Comment by alex2534alex** [comment]
Pleeaase, do it for me :З

**Comment by alex2534alex** [comment]
@PEMapModder , can u do this?

**Comment by alex2534alex** [comment]
+...:
If SimpleAuth data of player don't found - kick.
If all done successfuly - ban player (because he has done what was required)

**Comment by alex2534alex** [comment]
@Flavius12 , @PEMapModder , can you do this? :З

**Comment by legoboy0215** [comment]
Stop tagging people.
