### ISSUE TITLE
messages 

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#7]
I have included "password-confirm-required: true", but the message "Please register with /register password " Incorrect text

**Comment by Flavius12** [comment]
Thank you for report, I'll check the code later

**Comment by Pub4Game** [comment]
@Flavius12 please fix)

**Comment by Flavius12** [comment]
Yes. I'm preparing the new update

**Comment by Flavius12** [comment]
Fixed in v1.11! :D
