### ISSUE TITLE
 conversion date in the database

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#70]
![image](https://cloud.githubusercontent.com/assets/11244874/12538338/f64e9788-c2f0-11e5-83dd-083f2bec9865.png)

If you can tell me how to do it now, I tried, but I failed

**Comment by Flavius12** [comment]
``` php
date("d/m/Y H:i:s", $that_value);
```

**Comment by PEMapModder** [comment]
You can use `FROM_UNIXTIME(lastlogin)`

**Comment by Pub4Game** [comment]
thanks :+1:
