### ISSUE TITLE
PHP 7 error

### ISSUE THREAD

**Issue by andris155** [EvolSoft/ServerAuth#78]
12.02 21:48:38 [Server] INFO [Tag]kivi884: csak a pvp hülyült be ?
12.02 21:48:38 [Server] INFO Notice: Undefined offset: 0 in phar:///plugins/ServerAuth_v2.11.phar/src/ServerAuth/EventListener.php on line 112
12.02 21:48:38 [Server] INFO Notice: Undefined offset: 1 in phar:///plugins/ServerAuth_v2.11.phar/src/ServerAuth/EventListener.php on line 112
12.02 21:48:38 [Server] INFO Notice: Undefined offset: 2 in phar:///plugins/ServerAuth_v2.11.phar/src/ServerAuth/EventListener.php on line 112
12.02 21:48:38 [Server] INFO Notice: Undefined offset: 3 in phar:///plugins/ServerAuth_v2.11.phar/src/ServerAuth/EventListener.php on line 112
12.02 21:48:38 [Server] INFO Notice: Undefined offset: 4 in phar:///plugins/ServerAuth_v2.11.phar/src/ServerAuth/EventListener.php on line 112
12.02 21:48:38 [Server] INFO Notice: Undefined offset: 5 in phar:///plugins/ServerAuth_v2.11.phar/src/ServerAuth/EventListener.php on line 112

**Comment by Pub4Game** [comment]
https://github.com/EvolSoft/ServerAuth/issues/77

**Comment by andris155** [comment]
Thanks!
