### ISSUE TITLE
Low tps

### ISSUE THREAD

**Issue by andris155** [EvolSoft/ServerAuth#79]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/13028831/afa1ac1e-d27a-11e5-80b4-3beabacde3b4.PNG)
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/13261935/aea3819e-da62-11e5-94ab-feb97c3fd57f.PNG)

**Comment by Flavius12** [comment]
What version of ServerAuth are you using?

**Comment by PEMapModder** [comment]
Is the off-topic question in any ways related to this issue? He is using /timings.

**Comment by andris155** [comment]
ServerAuth 2.13

**Comment by Pub4Game** [comment]
I think this is due to the `enable-max-ip`. Because verified by a large count of files.
