### ISSUE TITLE
Crafting something before login？

### ISSUE THREAD

**Issue by daimeng02** [EvolSoft/ServerAuth#80]
Why I can crafting anything before login?for example，a player have some wood，and another player can make wood become sticks by crafting ，without login .Can u fix it？

**Comment by Pub4Game** [comment]
Use last version plugin.

**Comment by daimeng02** [comment]
Umm,I already use last version (2.13)

**Comment by Pub4Game** [comment]
Uhh.. Developer has removed this feature

**Comment by daimeng02** [comment]
I already use 2.12,Its OK now. but Why developer remove that,Is there a bug with it?

**Comment by Flavius12** [comment]
Yes. It crashes
