### ISSUE TITLE
PHP7 Support?

### ISSUE THREAD

**Issue by AndreyNazarchuk** [EvolSoft/ServerAuth#84]
Hello, when do you plan to allow this plugin php7 support? it works, but constantly shows notices.

**Comment by Flavius12** [comment]
Which notices do you see?

**Comment by AndreyNazarchuk** [comment]
Undefined offset, line 112

**Comment by Flavius12** [comment]
@AndreyNazarchuk offset 112 of which file?

**Comment by Michael-Tanjuakio** [comment]
[18:22:38] [Server thread/ERROR]: Could not load plugin 'ServerAuth': Incompatible API version
When I install the plugin it will show up this(same problem with php7)

**Comment by AndreyNazarchuk** [comment]
I think it's ServerAuth.PHP, but it happens every time someone logs in.

**Comment by AndreyNazarchuk** [comment]
scratch that, it happens every time someone chats.

**Comment by TheDiamondYT1** [comment]
Incompatible API is an easy to fix.
