### ISSUE TITLE
xenforo support?

### ISSUE THREAD

**Issue by shukenmg** [EvolSoft/ServerAuth#86]
how can I link mcpe server accounts to xenforo like minepocket

**Comment by legoboy0215** [comment]
Do it yourself?

**Comment by shukenmg** [comment]
how

**Comment by legoboy0215** [comment]
Make an addon yourself that does that.

**Comment by shukenmg** [comment]
how do i make an addon 
could you give me a tutorial (or a link)

thx

**Comment by shukenmg** [comment]
do i need to link mysql ?
if so, how?

**Comment by PEMapModder** [comment]
A XenForo addon.

**Comment by Flavius12** [comment]
I don't have XenForo otherwise I would write a XenForo addon

**Comment by legoboy0215** [comment]
Get the demo :P

**Comment by PEMapModder** [comment]
@legoboy0215 I don't think the demo allows you to install custom plugins.

**Comment by PEMapModder** [comment]
Write your own forum software! :P

**Comment by legoboy0215** [comment]
Get a nulled one. For dev purposes.
