### ISSUE TITLE
serverauth web manager bug (i think)

### ISSUE THREAD

**Issue by shukenmg** [EvolSoft/ServerAuth#87]
https://onedrive.live.com/redir?resid=3C36B519014C08CA!469&authkey=!AFNRXaiSKMzY00w&v=3&ithint=photo%2cPNG

I get this at serverauth web account how to fix?

thx

**Comment by SalmonGER** [comment]
I also have this issue.

**Comment by SalmonDE** [comment]
I also had this issue until now. I forgot to configure the config.yml in the plugins folder on my server. If you do that it should work.

**Comment by shukenmg** [comment]
fixed!!!

thx
