### ISSUE TITLE
Same user name annoying issue.

### ISSUE THREAD

**Issue by legoboy0215** [EvolSoft/ServerAuth#90]
When someone logins as the same username as you, they get kicked but you would need to login again.

**Comment by Flavius12** [comment]
force-single-session option seems working only on PocketMine and not on other forks. I didn't find any way to fix this because if I fix this for PocketMine it doesn't work on other forks and viceversa

**Comment by legoboy0215** [comment]
I used it on PocketMine. I am a loyal user XD

**Comment by Flavius12** [comment]
xD

**Comment by PEMapModder** [comment]
That's why I added this :P https://github.com/PEMapModder/HereAuth/blob/master/src/HereAuth/HereAuth.php#L78
