### ISSUE TITLE
xenforo

### ISSUE THREAD

**Issue by shukenmg** [EvolSoft/ServerAuth#93]
xenforo stores usernames and passwords in 2 different mysql tables

the first one is 

xf_user

second one is 

xf_user_authenticate  

now what i want to do is to make serverauth look for passwords and usernames there.
in that way users will have to register to join my server.

but how do i do that since i don't know the hash.

can somebody help me!!!

**Comment by legoboy0215** [comment]
This is not a Plugin Development forums. Please stop spamming issues...

**Comment by shukenmg** [comment]
oh

im soo sorry

i will stop

sorry

**Comment by Flavius12** [comment]
Thanks for your suggestion but don't forget that this is not the right place to post your Plugin Development questions
