### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kkekof** [EvolSoft/ServerAuth#98]
When i send pass, plugin say "Error"
http://i.imgur.com/cj0MFIX.jpg

**Comment by Flavius12** [comment]
Are you trying to use it with MySQL?

**Comment by kkekof** [comment]
Yes, i use mysql and all pl on mysql db

**Comment by Flavius12** [comment]
Maybe you configured it wrongly. Check your configuration

**Comment by kkekof** [comment]
it`s not a config, i dont delete hash() :D

**Comment by Flavius12** [comment]
Is your problem solved now?

**Comment by maomc** [comment]
**# When you can give a video tutorial？**

**Comment by Flavius12** [comment]
I don't think I can make one now. I'm too busy to make a video tutorial. However there are already many tutorials about ServerAuth on YouTube
